# Form implementation generated from reading ui file 'dizainas.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(445, 558)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pavadinimas = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.pavadinimas.setGeometry(QtCore.QRect(30, 90, 291, 41))
        self.pavadinimas.setObjectName("pavadinimas")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 151, 16))
        self.label_2.setObjectName("label_2")
        self.mygtukas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mygtukas.setGeometry(QtCore.QRect(330, 90, 91, 41))
        self.mygtukas.setObjectName("mygtukas")
        self.kiekis = QtWidgets.QLabel(parent=self.centralwidget)
        self.kiekis.setEnabled(False)
        self.kiekis.setGeometry(QtCore.QRect(210, 30, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kiekis.setFont(font)
        self.kiekis.setObjectName("kiekis")
        self.sarasas = QtWidgets.QListWidget(parent=self.centralwidget)
        self.sarasas.setGeometry(QtCore.QRect(30, 150, 391, 351))
        self.sarasas.setObjectName("sarasas")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 445, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aplikacija"))
        self.label.setText(_translate("MainWindow", "Produktų sąrašas"))
        self.label_2.setText(_translate("MainWindow", "Įveskite produkto pavadinimą"))
        self.mygtukas.setText(_translate("MainWindow", "Įvesti"))
        self.kiekis.setText(_translate("MainWindow", "(x)"))
