# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(628, 639)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lentele = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.lentele.setGeometry(QtCore.QRect(20, 160, 581, 431))
        self.lentele.setMinimumSize(QtCore.QSize(581, 0))
        self.lentele.setMaximumSize(QtCore.QSize(581, 16777215))
        self.lentele.setObjectName("lentele")
        self.lentele.setColumnCount(3)
        self.lentele.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.lentele.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lentele.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lentele.setHorizontalHeaderItem(2, item)
        self.lentele.horizontalHeader().setDefaultSectionSize(180)
        self.pavadinimas = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.pavadinimas.setGeometry(QtCore.QRect(20, 40, 581, 31))
        self.pavadinimas.setObjectName("pavadinimas")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 211, 16))
        self.label.setObjectName("label")
        self.kaina = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.kaina.setGeometry(QtCore.QRect(20, 100, 101, 31))
        self.kaina.setObjectName("kaina")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 201, 16))
        self.label_2.setObjectName("label_2")
        self.kiekis = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.kiekis.setGeometry(QtCore.QRect(150, 100, 111, 31))
        self.kiekis.setObjectName("kiekis")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 80, 47, 13))
        self.label_3.setObjectName("label_3")
        self.prideti = QtWidgets.QPushButton(parent=self.centralwidget)
        self.prideti.setGeometry(QtCore.QRect(530, 100, 71, 31))
        self.prideti.setObjectName("prideti")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 628, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Apskaitos programa"))
        self.lentele.setSortingEnabled(True)
        item = self.lentele.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Produkto pavadinimas"))
        item = self.lentele.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Kaina"))
        item = self.lentele.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Kiekis"))
        self.label.setText(_translate("MainWindow", "Produkto pavadinimas:"))
        self.label_2.setText(_translate("MainWindow", "Kaina"))
        self.label_3.setText(_translate("MainWindow", "Kiekis"))
        self.prideti.setText(_translate("MainWindow", "Pridėti"))
