# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(504, 180)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.kiekis = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.kiekis.setGeometry(QtCore.QRect(170, 50, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kiekis.setFont(font)
        self.kiekis.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.kiekis.setObjectName("kiekis")
        self.pliusas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pliusas.setGeometry(QtCore.QRect(350, 50, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pliusas.setFont(font)
        self.pliusas.setObjectName("pliusas")
        self.minusas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.minusas.setGeometry(QtCore.QRect(100, 50, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.minusas.setFont(font)
        self.minusas.setObjectName("minusas")
        self.zinute = QtWidgets.QLabel(parent=self.centralwidget)
        self.zinute.setGeometry(QtCore.QRect(100, 100, 311, 41))
        self.zinute.setText("")
        self.zinute.setObjectName("zinute")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 504, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.kiekis.setText(_translate("MainWindow", "0"))
        self.pliusas.setText(_translate("MainWindow", "+"))
        self.minusas.setText(_translate("MainWindow", "-"))
