# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(727, 530)
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(14)
        Dialog.setFont(font)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.mygtukai = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.mygtukai.setGeometry(QtCore.QRect(350, 470, 341, 32))
        self.mygtukai.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.mygtukai.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.mygtukai.setObjectName("mygtukai")
        self.laukelis = QtWidgets.QLineEdit(parent=Dialog)
        self.laukelis.setGeometry(QtCore.QRect(60, 80, 601, 41))
        self.laukelis.setObjectName("laukelis")

        self.retranslateUi(Dialog)
        self.mygtukai.accepted.connect(Dialog.accept) # type: ignore
        self.mygtukai.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Mano Pirma Aplikacija"))
